# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: destroyApp
  displayName: Delete App from k8s
  steps:
  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: 'latest'
  - task: aws-eks-authenticator@0
    inputs:
      clusterName: 'mundose-eks-pin'
      awsCredentials: 'eks-service-connection'
      regionName: 'us-east-1'
  - task: CmdLine@2
    displayName: kubeconfig was configured
    inputs:
      script: |
        aws eks --region us-east-1 update-kubeconfig --name mundose-eks-pin
      failOnStderr: true
  - task: CmdLine@2
    displayName: Destroy the app from k8s cluster
    inputs:
      script: |
        kubectl delete -f deployment/
      failOnStderr: true

- job: destroyEKS
  displayName: Destroy eks cluster
  dependsOn: destroyApp
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        commandOptions: '-backend=true -force-copy -get=true -input=false'
        backendServiceAWS: 'amazon-console-azure'
        backendAWSBucketName: 'devops-pin-terraform-files'
        backendAWSKey: 'eks/terraform.tfstate'
    - task: TerraformTaskV2@2
      displayName: Terraform destroy
      inputs:
        provider: 'aws'
        command: 'destroy'
        environmentServiceNameAWS: 'amazon-console-azure'

- job: destroyEc2Resources
  displayName: Destroy ec2 resources
  dependsOn: destroyEKS
  pool: 
    vmImage: ubuntu-latest
  steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        commandOptions: '-backend=true -force-copy -get=true -input=false'
        backendServiceAWS: 'amazon-console-azure'
        backendAWSBucketName: 'devops-pin-terraform-files'
        backendAWSKey: 'ec2/terraform.tfstate'
    - task: TerraformTaskV2@2
      displayName: Terraform destroy
      inputs:
        provider: 'aws'
        command: 'destroy'
        environmentServiceNameAWS: 'amazon-console-azure'